---
- name: Ensure _seatd group exists
  ansible.builtin.group:
    name: _seatd
    system: true

- name: Create kiosk user
  ansible.builtin.user:
    name: "{{ kioskkit_user }}"
    system: false
    create_home: true
    shell: /bin/bash
    groups: video,input,render,_seatd
    password: "!"
    password_lock: true
