---
- name: Create kiosk user
  ansible.builtin.user:
    name: "{{ kioskkit_user }}"
    system: true
    create_home: true
    shell: /bin/bash
    groups: video,input,render,_seatd
    password: "!"
    password_lock: true
